'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Share2, Sun, Moon, Monitor, Download, FileJson } from 'lucide-react';
import { AnimatedLogo } from '@/components/AnimatedLogo';
import { useRef } from 'react';
import Lottie from 'lottie-react';
import animationData from '@/data/dna-loading.json';
import animationDataOnlySquare from '@/data/animation-dna-only-square.json';
import animationDataSquareClean from '@/data/animation-square-clean.json';
import animationDataNew from '@/data/animation-dna-data.json';
// ============================================
// ANIMATED LOGO DNA PREVIEW
// ============================================
export function AnimatedLogoDNAPreview() {
    const [isRecording, setIsRecording] = useState(false);
    const canvasContainerRef = useRef<HTMLDivElement>(null);

    const handleDownloadVideo = () => {
        if (!canvasContainerRef.current) return;
        
        setIsRecording(true);
        
        // Find the canvas element generated by lottie-react
        const canvas = canvasContainerRef.current.querySelector("canvas");
        if (!canvas || canvas.width === 0 || canvas.height === 0) {
            console.error("Canvas element not found or has 0 dimension", canvas?.width);
            alert("Aguarde a animação carregar completamente antes de gravar.");
            setIsRecording(false);
            return;
        }

        // We want a white background for the recording instead of transparent
        const recordingCanvas = document.createElement("canvas");
        recordingCanvas.width = canvas.width;
        recordingCanvas.height = canvas.height;
        const ctx = recordingCanvas.getContext("2d");

        // Use a continuous loop to draw the lottie canvas onto our opaque canvas
        let frameId: number;
        
        const drawFrame = () => {
            if (ctx && canvas.width > 0 && canvas.height > 0) {
                // Ensure recordingCanvas matches true dimensions
                if (recordingCanvas.width !== canvas.width) {
                    recordingCanvas.width = canvas.width;
                    recordingCanvas.height = canvas.height;
                }
                
                ctx.fillStyle = "#ffffff";
                ctx.fillRect(0, 0, recordingCanvas.width, recordingCanvas.height);
                ctx.drawImage(canvas, 0, 0);
            }
            if (isRecording) {
                frameId = requestAnimationFrame(drawFrame);
            }
        };
        frameId = requestAnimationFrame(drawFrame);

        const stream = recordingCanvas.captureStream(60);
        
        let mimeType = "video/webm";
        let fileExtension = "webm";
        
        // Try to use MP4/H264 if browser allows it (e.g. Safari or modern Chrome with specific flags)
        if (MediaRecorder.isTypeSupported("video/mp4")) {
            mimeType = "video/mp4";
            fileExtension = "mp4";
        } else if (MediaRecorder.isTypeSupported("video/mp4;codecs=avc1")) {
            mimeType = "video/mp4;codecs=avc1";
            fileExtension = "mp4";
        }
        
        const mediaRecorder = new MediaRecorder(stream, { mimeType });
        const chunks: BlobPart[] = [];

        mediaRecorder.ondataavailable = (e) => {
            if (e.data.size > 0) chunks.push(e.data);
        };

        mediaRecorder.onstop = () => {
            cancelAnimationFrame(frameId);
            const blob = new Blob(chunks, { type: mimeType });
            if (blob.size === 0) {
                 console.error("Generated Blob is 0 bytes!");
                 setIsRecording(false);
                 return;
            }
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `animacao-logo-nutribuddy.${fileExtension}`;
            a.click();
            URL.revokeObjectURL(url);
            setIsRecording(false);
        };

        // Start recording and force a data push every 100ms
        mediaRecorder.start(100);

        // Stop recording after 3 seconds (one or more full loops depending on speed)
        setTimeout(() => {
            if (mediaRecorder.state !== "inactive") {
                mediaRecorder.requestData(); // Flush remaining
                mediaRecorder.stop();
            }
        }, 3000);
    };

    return (
        <div className="w-full h-full flex flex-col items-center justify-center bg-gradient-to-br from-neutral-50 to-neutral-100 p-6 gap-6 overflow-hidden">
            <div className="p-8 bg-white border border-neutral-200 rounded-lg shadow-sm flex items-center justify-center min-w-[300px] min-h-[300px] overflow-hidden">
                <AnimatedLogo size={300} />
            </div>

            {/* Hidden Lottie rendering to Canvas specifically for recording */}
            <div className="overflow-hidden w-[1px] h-[1px] opacity-0 absolute pointer-events-none">
                <div ref={canvasContainerRef} style={{ width: 600, height: 600 }}>
                    <Lottie 
                        animationData={animationData} 
                        loop={true} 
                        // eslint-disable-next-line @typescript-eslint/no-explicit-any
                        renderer={"canvas" as any}
                        rendererSettings={{
                            preserveAspectRatio: "xMidYMid meet"
                        }}
                        style={{ width: 1000, height: 1000 }} // high res recording
                    />
                </div>
            </div>

            <Button 
                onClick={handleDownloadVideo}
                disabled={isRecording}
                className="gap-2 bg-neutral-900 hover:bg-neutral-800 text-white"
            >
                <Download className="w-4 h-4" />
                {isRecording ? "Gravando animação..." : "Baixar Vídeo (MP4/WebM)"}
            </Button>
            <p className="text-xs text-neutral-500 max-w-xs text-center font-mono">
                Será salvo em MP4 se seu navegador suportar nativamente (como Safari/Edge). Caso contrário, salva no formato otimizado WebM.
            </p>
        </div>
    );
}

// ============================================
// ANIMATE TABS PREVIEW
// ============================================
export function AnimateTabsPreview() {
    return (
        <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-neutral-50 to-neutral-100 p-6">
            <div className="w-full max-w-sm">
                <Tabs defaultValue="account" className="w-full">
                    <TabsList className="grid w-full grid-cols-2">
                        <TabsTrigger value="account">Account</TabsTrigger>
                        <TabsTrigger value="password">Password</TabsTrigger>
                    </TabsList>
                    <Card className="mt-4">
                        <TabsContent value="account" className="m-0">
                            <CardHeader>
                                <CardTitle>Account</CardTitle>
                                <CardDescription>Make changes to your account here.</CardDescription>
                            </CardHeader>
                            <CardContent className="space-y-2">
                                <div className="space-y-1">
                                    <Label htmlFor="name">Name</Label>
                                    <Input id="name" defaultValue="Pedro Duarte" />
                                </div>
                            </CardContent>
                            <CardFooter>
                                <Button>Save changes</Button>
                            </CardFooter>
                        </TabsContent>
                        <TabsContent value="password" className="m-0">
                            <CardHeader>
                                <CardTitle>Password</CardTitle>
                                <CardDescription>Change your password here.</CardDescription>
                            </CardHeader>
                            <CardContent className="space-y-2">
                                <div className="space-y-1">
                                    <Label htmlFor="current">Current password</Label>
                                    <Input id="current" type="password" />
                                </div>
                                <div className="space-y-1">
                                    <Label htmlFor="new">New password</Label>
                                    <Input id="new" type="password" />
                                </div>
                            </CardContent>
                            <CardFooter>
                                <Button>Save password</Button>
                            </CardFooter>
                        </TabsContent>
                    </Card>
                </Tabs>
            </div>
        </div>
    );
}

// ============================================
// SHARE BUTTON PREVIEW
// ============================================
export function ShareButtonPreview() {
    const [shared, setShared] = useState(false);

    return (
        <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-neutral-50 to-neutral-100">
            <motion.div
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
            >
                <Button
                    variant={shared ? "default" : "outline"}
                    className="gap-2"
                    onClick={() => {
                        setShared(true);
                        setTimeout(() => setShared(false), 2000);
                    }}
                >
                    <AnimatePresence mode="wait">
                        {shared ? (
                            <motion.span
                                key="shared"
                                initial={{ opacity: 0, scale: 0.5 }}
                                animate={{ opacity: 1, scale: 1 }}
                                exit={{ opacity: 0, scale: 0.5 }}
                                className="flex items-center gap-2"
                            >
                                ✓ Shared!
                            </motion.span>
                        ) : (
                            <motion.span
                                key="share"
                                initial={{ opacity: 0, scale: 0.5 }}
                                animate={{ opacity: 1, scale: 1 }}
                                exit={{ opacity: 0, scale: 0.5 }}
                                className="flex items-center gap-2"
                            >
                                <Share2 className="w-4 h-4" />
                                Share
                            </motion.span>
                        )}
                    </AnimatePresence>
                </Button>
            </motion.div>
        </div>
    );
}

// ============================================
// THEME TOGGLER PREVIEW
// ============================================
export function ThemeTogglerPreview() {
    const [theme, setTheme] = useState<'light' | 'dark' | 'system'>('light');

    const icons = {
        light: Sun,
        dark: Moon,
        system: Monitor,
    };

    const nextTheme = () => {
        const order: ('light' | 'dark' | 'system')[] = ['light', 'dark', 'system'];
        const currentIndex = order.indexOf(theme);
        setTheme(order[(currentIndex + 1) % order.length]);
    };

    const Icon = icons[theme];

    return (
        <div className="w-full h-full flex flex-col items-center justify-center gap-4 bg-gradient-to-br from-neutral-50 to-neutral-100">
            <motion.div
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
            >
                <Button
                    variant="outline"
                    size="icon"
                    onClick={nextTheme}
                    className="w-12 h-12"
                >
                    <AnimatePresence mode="wait">
                        <motion.div
                            key={theme}
                            initial={{ rotate: -90, opacity: 0 }}
                            animate={{ rotate: 0, opacity: 1 }}
                            exit={{ rotate: 90, opacity: 0 }}
                            transition={{ duration: 0.2 }}
                        >
                            <Icon className="w-5 h-5" />
                        </motion.div>
                    </AnimatePresence>
                </Button>
            </motion.div>
            <p className="text-sm text-muted-foreground capitalize">{theme} mode</p>
        </div>
    );
}

// ============================================
// HEADLESS POPOVER PREVIEW
// ============================================
export function HeadlessPopoverPreview() {
    return (
        <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-neutral-50 to-neutral-100">
            <Popover>
                <PopoverTrigger asChild>
                    <Button variant="outline">Open popover</Button>
                </PopoverTrigger>
                <PopoverContent className="w-80">
                    <div className="grid gap-4">
                        <div className="space-y-2">
                            <h4 className="font-medium leading-none">Dimensions</h4>
                            <p className="text-sm text-muted-foreground">
                                Set the dimensions for the layer.
                            </p>
                        </div>
                        <div className="grid gap-2">
                            <div className="grid grid-cols-3 items-center gap-4">
                                <Label htmlFor="width">Width</Label>
                                <Input id="width" defaultValue="100%" className="col-span-2 h-8" />
                            </div>
                            <div className="grid grid-cols-3 items-center gap-4">
                                <Label htmlFor="height">Height</Label>
                                <Input id="height" defaultValue="25px" className="col-span-2 h-8" />
                            </div>
                        </div>
                    </div>
                </PopoverContent>
            </Popover>
        </div>
    );
}

// ============================================
// ANIMATED LOGO DNA ONLY SQUARE PREVIEW
// ============================================
export function AnimatedLogoOnlySquarePreview() {
    const handleDownloadJson = () => {
        const blob = new Blob([JSON.stringify(animationDataOnlySquare)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "animation-dna-only-square.json";
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="w-full h-full flex flex-col items-center justify-center bg-gradient-to-br from-neutral-50 to-neutral-100 p-6 gap-6 overflow-hidden">
            <div className="p-8 bg-white border border-neutral-200 rounded-lg shadow-sm flex items-center justify-center min-w-[300px] min-h-[300px] overflow-hidden">
                <div style={{ width: 300, height: 300 }}>
                    <Lottie 
                        animationData={animationDataOnlySquare} 
                        loop={true} 
                        rendererSettings={{ preserveAspectRatio: "xMidYMid meet" }}
                        style={{ width: "100%", height: "100%" }}
                    />
                </div>
            </div>
            
            <div className="flex flex-col items-center gap-3">
                <Button 
                    onClick={handleDownloadJson}
                    className="gap-2 bg-neutral-900 hover:bg-neutral-800 text-white"
                >
                    <FileJson className="w-4 h-4" />
                    Baixar Arquivo JSON (~30KB)
                </Button>
                <p className="text-xs text-neutral-500 max-w-xs text-center font-mono">
                    Animação DNA - Only Square
                </p>
            </div>
        </div>
    );
}

// ============================================
// ANIMATED LOGO SQUARE CLEAN PREVIEW
// ============================================
export function AnimatedLogoSquareCleanPreview() {
    const handleDownloadJson = () => {
        const blob = new Blob([JSON.stringify(animationDataSquareClean)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "animation-square-clean.json";
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="w-full h-full flex flex-col items-center justify-center bg-gradient-to-br from-neutral-50 to-neutral-100 p-6 gap-6 overflow-hidden">
            <div className="p-8 bg-white border border-neutral-200 rounded-lg shadow-sm flex items-center justify-center min-w-[300px] min-h-[300px] overflow-hidden">
                <div style={{ width: 300, height: 300 }}>
                    <Lottie 
                        animationData={animationDataSquareClean} 
                        loop={true} 
                        rendererSettings={{ preserveAspectRatio: "xMidYMid meet" }}
                        style={{ width: "100%", height: "100%" }}
                    />
                </div>
            </div>
            
            <div className="flex flex-col items-center gap-3">
                <Button 
                    onClick={handleDownloadJson}
                    className="gap-2 bg-neutral-900 hover:bg-neutral-800 text-white"
                >
                    <FileJson className="w-4 h-4" />
                    Baixar Arquivo JSON (~33KB)
                </Button>
                <p className="text-xs text-neutral-500 max-w-xs text-center font-mono">
                    Animação DNA - Square Clean
                </p>
            </div>
        </div>
    );
}

// ============================================
// ANIMATED LOGO DATA PREVIEW
// ============================================
export function AnimatedLogoDataPreview() {
    const handleDownloadJson = () => {
        const blob = new Blob([JSON.stringify(animationDataNew)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "animation-dna-data.json";
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="w-full h-full flex flex-col items-center justify-center bg-gradient-to-br from-neutral-50 to-neutral-100 p-6 gap-6 overflow-hidden">
            <div className="p-8 bg-white border border-neutral-200 rounded-lg shadow-sm flex items-center justify-center min-w-[300px] min-h-[300px] overflow-hidden">
                <div style={{ width: 300, height: 300 }}>
                    <Lottie 
                        animationData={animationDataNew} 
                        loop={true} 
                        rendererSettings={{ preserveAspectRatio: "xMidYMid meet" }}
                        style={{ width: "100%", height: "100%" }}
                    />
                </div>
            </div>
            
            <div className="flex flex-col items-center gap-3">
                <Button 
                    onClick={handleDownloadJson}
                    className="gap-2 bg-neutral-900 hover:bg-neutral-800 text-white"
                >
                    <FileJson className="w-4 h-4" />
                    Baixar Arquivo JSON (~32KB)
                </Button>
                <p className="text-xs text-neutral-500 max-w-xs text-center font-mono">
                    Animação DNA - Data
                </p>
            </div>
        </div>
    );
}

// Default export for lazy loading
export default AnimatedLogoDNAPreview;
